### ISSUE TITLE
Error when creating smb share

### ISSUE THREAD

**Issue by bsauvajon** [purestorage/purity_fb_python_client#20]
Hello,

I made a script to create a volume shared on smb with native acl mode, and I've got this error

HTTP response headers: HTTPHeaderDict({'Content-Length': '83', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Expires': '0', 'Server': 'nginx/1.4.6 (Ubuntu)', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Date': 'Tue, 26 Nov 2019 15:42:41 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json;charset=UTF-8'})
HTTP response body: {"errors":[{"code":3,"context":null,"message":"Unrecognized field \"acl-mode\" "}]}

It seems the python module send a field called "acl-mode" for smb, but if you list a filesystem through the flashblade api, the member is called "acl_mode", isn't it a mistake  in the smb_rule model definition ?

**Comment by jsalomon617** [comment]
Yes, that seems to be a small error in our REST client.  We'll make sure to fix that in our next release.

**Comment by jsalomon617** [comment]
With the latest release, this should now be fixed.
