### ISSUE TITLE
Not compatible with Python 3.7 and higher

### ISSUE THREAD

**Issue by sdodsley** [purestorage/purity_fb_python_client#25]
It appears that when replication was added to the latest purity_fb python SDK the word `async` has been used.
https://github.com/purestorage/purity_fb_python_client/blob/master/purity_fb/purity_fb_1dot9/models/performance_replication.py#L47 
This makes `purity_fb` incompatible with Python3.7 and 3.8 where `async` is a reserved keyword.

**Comment by ychen-ps** [comment]
[REST 1.12.2 Python SDK](https://github.com/purestorage/purity_fb_python_client/releases/tag/v1.12.2) is made to be compatible with Python 3.7 and higher.
