### ISSUE TITLE
"created" attribute is missing from FileSystemSnapshot in 1dot9 version of file_system_snapshot.py

### ISSUE THREAD

**Issue by joschafer** [purestorage/purity_fb_python_client#31]
This attribute seems to be available in the rest API but not in this file,  It is the only removed attribute from 1.8

Here is the relevant change (swagger as example)

1.8 version of swagger types
swagger_types = {
        'name': 'str',
        'created': 'int',
        'id': 'str',
        'destroyed': 'bool',
        'policy': 'FixedReferenceWithId',
        'source': 'str',
        'source_destroyed': 'bool',
        'source_id': 'str',
        'suffix': 'str',
        'time_remaining': 'int'
    }

1.9 version of swagger types
    swagger_types = {
        'name': 'str',
        'id': 'str',
        'destroyed': 'bool',
        'owner': 'Reference',
        'owner_destroyed': 'bool',
        'policy': 'LocationReference',
        'source': 'str',
        'source_destroyed': 'bool',
        'source_id': 'str',
        'source_is_local': 'bool',
        'source_location': 'Reference',
        'source_display_name': 'str',
        'suffix': 'str',
        'time_remaining': 'int'
    }

Please let me know if I missed something or if I need to provide additional information.

**Comment by ychen-ps** [comment]
This is fixed in version 1.12.3.
